In [1]:
from scipy.optimize import minimize
import matplotlib.pyplot as plt
import numpy as np
import random


In [2]:
np.random.seed(100)
classA = np.concatenate((
    np.random.randn(10, 2) * 0.2 + [1.5, 0.5],
    np.random.randn(10, 2) * 0.2 + [-1.5, 0.5]
))

np.random.seed(100)
classB = np.random.randn(20, 2) * 0.2 + [0.0, -0.5]

inputs = np.concatenate((classA, classB))
targets = np.concatenate((
    np.ones(classA.shape[0]),
    -np.ones(classB.shape[0])
))

np.random.seed(100)
N = inputs.shape[0]  # Number of rows (samples)
permute = list(range(N))
random.shuffle(permute)

inputs = inputs[permute, :]
targets = targets[permute]

In [3]:
print(inputs)
print(targets)

[[-0.06524761 -0.4888648 ]
 [ 1.41237288  0.27633635]
 [ 1.73060716  0.44951279]
 [ 1.69626416  0.60284377]
 [ 1.15004691  0.56853608]
 [-0.0916054  -0.4129673 ]
 [-1.46309626  0.68741644]
 [ 1.46210083  0.55100029]
 [-0.34995309 -0.43146392]
 [-0.15127046 -0.3367092 ]
 [ 1.38328099  0.66336941]
 [-1.55037583  0.33151285]
 [-1.35379993  0.77231123]
 [-1.45552008  0.2113566 ]
 [ 0.14620007 -0.22768877]
 [-0.08762712 -0.72366365]
 [ 0.04447992 -0.7886434 ]
 [ 0.15008895 -0.59118939]
 [-0.10625608 -0.29405346]
 [ 1.39374392  0.70594654]
 [ 0.32379633 -0.19167897]
 [ 0.23060716 -0.55048721]
 [ 0.23792445 -0.83812337]
 [ 0.19626416 -0.39715623]
 [-0.03789917 -0.44899971]
 [ 0.03690374 -0.31258356]
 [-0.05037583 -0.66848715]
 [-1.17620367  0.80832103]
 [ 1.63454416  0.47911777]
 [-1.56524761  0.5111352 ]
 [ 1.4083946   0.5870327 ]
 [-1.65127046  0.6632908 ]
 [-1.26207555  0.16187663]
 [-1.77127981  0.2535131 ]
 [-0.11671901 -0.33663059]
 [-0.27127981 -0.7464869 ]
 [-1.34991105  0.40881061]
 

In [19]:
degree = 0
degree if degree is not None else 2

0

In [4]:
bool(0)

False

In [5]:
from tools import SupportVectorMachine

svm = SupportVectorMachine(X=inputs, y=targets, kernel_type='linear')

In [6]:
svm.fit()

array([6.87889444e-16, 6.61464525e+00, 2.07719714e-14, 0.00000000e+00,
       3.23779006e-15, 0.00000000e+00, 1.27771656e-14, 5.61397218e-15,
       0.00000000e+00, 0.00000000e+00, 2.60748694e-15, 0.00000000e+00,
       1.20899114e-14, 0.00000000e+00, 0.00000000e+00, 6.46101372e-15,
       7.72012620e-15, 7.40440768e-15, 0.00000000e+00, 2.79208642e-15,
       1.12831186e+01, 7.39674281e-15, 6.58065646e-15, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 8.11277404e-15, 1.28932692e-14,
       9.80666176e-16, 9.91277876e-15, 5.37637879e-16, 1.34087708e-14,
       4.66847338e+00, 0.00000000e+00, 9.92737707e-16, 1.01732743e-14,
       0.00000000e+00, 0.00000000e+00, 5.89203548e-15, 6.13501881e-15])

In [7]:
alphas = svm.ret['x']
alphas

array([6.87889444e-16, 6.61464525e+00, 2.07719714e-14, 0.00000000e+00,
       3.23779006e-15, 0.00000000e+00, 1.27771656e-14, 5.61397218e-15,
       0.00000000e+00, 0.00000000e+00, 2.60748694e-15, 0.00000000e+00,
       1.20899114e-14, 0.00000000e+00, 0.00000000e+00, 6.46101372e-15,
       7.72012620e-15, 7.40440768e-15, 0.00000000e+00, 2.79208642e-15,
       1.12831186e+01, 7.39674281e-15, 6.58065646e-15, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 8.11277404e-15, 1.28932692e-14,
       9.80666176e-16, 9.91277876e-15, 5.37637879e-16, 1.34087708e-14,
       4.66847338e+00, 0.00000000e+00, 9.92737707e-16, 1.01732743e-14,
       0.00000000e+00, 0.00000000e+00, 5.89203548e-15, 6.13501881e-15])

In [8]:
nonzero_indices = np.where(alphas > 1e-5)[0]
type(nonzero_indices)

numpy.ndarray

In [9]:
# for idx in nonzero_indices:
#     print(idx)
print(svm.alpha[2])
print(svm.X[2])
print(svm.X.shape)
print(svm.X)

2.0771971373002606e-14
[1.73060716 0.44951279]
(40, 2)
[[-0.06524761 -0.4888648 ]
 [ 1.41237288  0.27633635]
 [ 1.73060716  0.44951279]
 [ 1.69626416  0.60284377]
 [ 1.15004691  0.56853608]
 [-0.0916054  -0.4129673 ]
 [-1.46309626  0.68741644]
 [ 1.46210083  0.55100029]
 [-0.34995309 -0.43146392]
 [-0.15127046 -0.3367092 ]
 [ 1.38328099  0.66336941]
 [-1.55037583  0.33151285]
 [-1.35379993  0.77231123]
 [-1.45552008  0.2113566 ]
 [ 0.14620007 -0.22768877]
 [-0.08762712 -0.72366365]
 [ 0.04447992 -0.7886434 ]
 [ 0.15008895 -0.59118939]
 [-0.10625608 -0.29405346]
 [ 1.39374392  0.70594654]
 [ 0.32379633 -0.19167897]
 [ 0.23060716 -0.55048721]
 [ 0.23792445 -0.83812337]
 [ 0.19626416 -0.39715623]
 [-0.03789917 -0.44899971]
 [ 0.03690374 -0.31258356]
 [-0.05037583 -0.66848715]
 [-1.17620367  0.80832103]
 [ 1.63454416  0.47911777]
 [-1.56524761  0.5111352 ]
 [ 1.4083946   0.5870327 ]
 [-1.65127046  0.6632908 ]
 [-1.26207555  0.16187663]
 [-1.77127981  0.2535131 ]
 [-0.11671901 -0.33663059]


In [10]:
print(svm.alpha)
print(svm.y)
print()
print(np.sum(svm.alpha * svm.y))

[6.87889444e-16 6.61464525e+00 2.07719714e-14 0.00000000e+00
 3.23779006e-15 0.00000000e+00 1.27771656e-14 5.61397218e-15
 0.00000000e+00 0.00000000e+00 2.60748694e-15 0.00000000e+00
 1.20899114e-14 0.00000000e+00 0.00000000e+00 6.46101372e-15
 7.72012620e-15 7.40440768e-15 0.00000000e+00 2.79208642e-15
 1.12831186e+01 7.39674281e-15 6.58065646e-15 0.00000000e+00
 0.00000000e+00 0.00000000e+00 8.11277404e-15 1.28932692e-14
 9.80666176e-16 9.91277876e-15 5.37637879e-16 1.34087708e-14
 4.66847338e+00 0.00000000e+00 9.92737707e-16 1.01732743e-14
 0.00000000e+00 0.00000000e+00 5.89203548e-15 6.13501881e-15]
[-1.  1.  1.  1.  1. -1.  1.  1. -1. -1.  1.  1.  1.  1. -1. -1. -1. -1.
 -1.  1. -1. -1. -1. -1. -1. -1. -1.  1.  1.  1.  1.  1.  1.  1. -1. -1.
  1.  1. -1. -1.]

7.105427357601002e-15


In [11]:
print(svm._indicator(svm.X[0]))
print(bool(svm.y[0]))

True
True


In [12]:
y_preds = svm.predict(inputs)
y_preds

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [13]:
svm.evaluate(y_preds, targets)

0.5